import path from 'path'
import pkg from './package.json'
import { defineConfig, loadEnv } from 'vite' // 使用 defineConfig 工具函数，这样不用 jsdoc 注解也可以获取类型提示
import autoGenerateDeclaration from 'vite-plugin-dts'
import { pathResolve } from './scripts/generate-index'

export default defineConfig({
  plugins: [
    autoGenerateDeclaration({
      rollupTypes: true, // 这个选项用于合并所有类型声明到一个文件中。如果为 false，则会为每个模块生成单独的 .d.ts 文件
      insertTypesEntry: true, // 会在编译后的目录下生成一个入口 index.d.ts 文件，便于用户引用类型声明
    }),
  ],
  build: {
    lib: {
      entry: pathResolve('src/index.ts'), // 库的入口文件
      // formats: ['es', 'cjs'],
      formats: ['es'],
      fileName: (format) => `${pkg.name}.${format}.js`, // 打包后的文件名格式
    },
  },
})
