import path from 'path'
import { defineConfig } from 'vite'
import autoGenerateDeclaration from 'vite-plugin-dts'

/** 路径拼接函数，简化代码 用 normalizePath 解决 window 下的路径问题 */
function pathResolve(dir: string): string {
  return path.normalize(path.resolve(process.cwd(), dir))
}

export default defineConfig({
  plugins: [
    autoGenerateDeclaration({
      rollupTypes: true, // 这个选项用于合并所有类型声明到一个文件中。如果为 false，则会为每个模块生成单独的 .d.ts 文件
      insertTypesEntry: true, // 会在编译后的目录下生成一个入口 index.d.ts 文件，便于用户引用类型声明
      // strictOutput: false, // 关闭严格模块声明（避免按格式拆分）
    }),
  ],

  resolve: {
    alias: [
      /** 设置 `@` 指向 `src` 目录 */
      { find: '@', replacement: pathResolve('src') },
      /** 设置 `#` 指向 `types` 目录 */
      { find: '#', replacement: pathResolve('types') },
    ],
  },

  build: {
    lib: {
      entry: pathResolve('src/index.ts'), // 库的入口文件
      formats: ['es', 'cjs'],
      // formats: ['es'],
      // fileName: (format) => `${pkg.name}.${format}.js`, // 打包后的文件名格式
      fileName: (format) => `index.${format}.js`, // 打包后的文件名格式
    },
    sourcemap: false,
  },
})
