import pkg from '../package.json'

export const version = pkg.version

export { to } from './function/to'
export { sleep } from './function/sleep'
export { deepClone } from './function/deepClone'
export { debounce } from './function/debounce'
export { throttle } from './function/throttle'
// 常量
export { MediaType } from './enums/media-type.enum'
export { TimeUnit } from './enums/time-unit.enum'
export { HttpStatus } from './enums/http-status.enum'
// 浏览器方法
export { linkDownload } from './browser/linkDownload'
// 字符串
export { upperFirst } from './string/upperFirst'
export { reverseString } from './string/reverseString'
// 对象
export { get } from './object/get'
export { pick } from './object/pick'
export { omit } from './object/omit'
// 数组
export { at } from './array/at'
export { unique } from './array/unique'
export { uniqueBy } from './array/uniqueBy'
export { first } from './array/first'
export { last } from './array/last'
export { difference } from './array/difference'
export { differenceBy } from './array/differenceBy'
// 随机
export { random } from './random/random'
export { randomBoolean } from './random/randomBoolean'
export { randomIndex } from './random/randomIndex'
// 校验
export { isBlob } from './validate/isBlob'
export { isBrowser } from './validate/isBrowser'
export { isRegExp } from './validate/isRegExp'
export { isEmpty } from './validate/isEmpty'
export { isNil } from './validate/isNil'
export { isNull } from './validate/isNull'
export { isUndefined } from './validate/isUndefined'
export { isBoolean } from './validate/isBoolean'
export { isDate } from './validate/isDate'
export { isHexColor } from './validate/isHexColor'
export { isLeapYear } from './validate/isLeapYear'
export { isSet } from './validate/isSet'
export { isMap } from './validate/isMap'
export { isWeakMap } from './validate/isWeakMap'
export { isSymbol } from './validate/isSymbol'
export { isString } from './validate/isString'
export { isPrimitive } from './validate/isPrimitive'
export { isNumber } from './validate/isNumber'
export { isInteger } from './validate/isInteger'
export { isFloat } from './validate/isFloat'
export { isStringNumber } from './validate/isStringNumber'
export { isStringBoolean } from './validate/isStringBoolean'
export { isPlainObject } from './validate/isPlainObject'
export { isObjectLike } from './validate/isObjectLike'
export { isArray } from './validate/isArray'
export { isFunction } from './validate/isFunction'
export { isPromise } from './validate/isPromise'
export { isUnsafeProperty } from './validate/isUnsafeProperty'
